spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cash_flows_db
    username: root
    password: LevshaNumberOne1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false
  mail:
    host: connect.smtp.bz
    port: 587
    username: aza0000167@gmail.com
    password: pymv6QC8VrlB
    properties:
      mail:
        from: support@dertix.net
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
application:
  security:
    oauth2:
      discord:
        client-id: 1194987139860017163
        client-secret: EubgOnWjYksaWWPDmAnbdWXcOnblevAq
        token-url: https://discord.com/api/v10/oauth2/token
        register-redirect-url: http://127.0.0.1:5500/authenticationPages/discordRegisterPage.html
        authentication-redirect-url: http://127.0.0.1:5500/authenticationPages/discordAuthPage.html
        verification-redirect-url: http://127.0.0.1:5500/authenticationPages/discordAddVerificatonPage.html
        user-url: https://discord.com/api/v10/users/@me
      github:
        access-token-url: https://github.com/login/oauth/access_token
        user-url: https://api.github.com/user
        login:
          client-id: d462fb12f03ed6d0a382
          client-secret: b745219c5c07bc34e802b1225e3a2fcd13136979
          redirect-url: http://127.0.0.1:5500/authenticationPages/githubAuthPage.html
        register:
          client-id: Ov23ctk0kM8yWRPCd2IO
          client-secret: 50bf7a33e6e19ac2061c199cd05b26491a7de460
          redirect-url: http://127.0.0.1:5500/authenticationPages/githubRegisterPage.html
        verification:
          client-id: Ov23lisxKq1raqpKWKnG
          client-secret: aa443e54b4ee76b682234f74fce80affda629d23
          redirect-url: http://127.0.0.1:5500/authenticationPages/githubAddVerificatonPage.html
    jwt:
      secret-key: 5eekxbfUrc9marV/33k0yzgFxcuIHwIJyQ/IUd7HOMA=
      access-token:
        expiration: 86400000
      refresh-token:
        expiration: 604800000 # 7 days
        remember-me-expiration: 6048000000