spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cash_flows_db
    username: root
    password: LevshaNumberOne1
application:
  main-page-url: http://127.0.0.1:5500/transactionPages/createTransaction.html
  verifications-page-url: http://127.0.0.1:5500/transactionPages/createTransaction.html